# Site settings
title: Geomechanics
description: "This is Vu Nguyen's personal website to summarize and share his knowleges about FEM, GEOTECH and to store his personal experiences in life."
baseurl: "geomechanics" 
url: "http:://quangvunp.github.io/geomechanics" 
tagline: A basic guide to Geomechanics

# Build settings
markdown: kramdown

#kramdown:
#    auto_ids: false 
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
